### ISSUE TITLE
头像上传之后显示不出来

### ISSUE THREAD

**Issue by LeoShanXiaojun** [91270/Meiam.System#11]
头像上传的本地路径是 
 "AvatarUpload": {
    "AvatarDirectory": "D://wwwroot/avatars",
    "AvatarUrl": "/"
  },
本地能保存成功，但是系统加载不出来

**Comment by 91270** [comment]
这个要指定到你前端的项目的路径中

**Comment by LeoShanXiaojun** [comment]
没太理解，
你是说 AvatarDirectory要指定到前端的项目的路径中吗
