### ISSUE TITLE
接口请求一直失败

### ISSUE THREAD

**Issue by wqqwqq666** [91270/Meiam.System#12]
前端后台都已经编译完成，登录之后一直显示接口请求失败。
后台后没有收到请求，断点没有进入
![1607049844(1)](https://user-images.githubusercontent.com/15796964/101115319-1db12700-361e-11eb-9387-8455c2a1785e.jpg)
但是前端又显示请求成功：
![1](https://user-images.githubusercontent.com/15796964/101115398-420d0380-361e-11eb-9a95-909632597fa3.png)
![4](https://user-images.githubusercontent.com/15796964/101115511-75e82900-361e-11eb-9c0a-e96eee1b7b48.png)

**Comment by 91270** [comment]
1、检查 Nlog.Config 文件配置
2、使用 控制台模式  调试启动程序  或   dotnet Meiam.System.Hostd.dll
3、根据你的截图你使用的是 IIS Express 模式启动程序，需要在 appsettings.json 重新配置 ApiUrl 地址，和 Web 端接口地址

**Comment by wqqwqq666** [comment]
可以了，是Nlog.Config 数据库连接的问题，哎，搞了一个月，有时间就调试，不如一个issue来的方便，一分钟就搞定了，感谢大佬：）

**Comment by AlexMercerGitHub** [comment]
+1，作者大大有教程地址吗，或者QQ群什么的
