### ISSUE TITLE
按钮页面的权限，比如控制页面是否隐藏，是否可用的配置页面

### ISSUE THREAD

**Issue by AlexMercerGitHub** [91270/Meiam.System#13]
这个是只做了api权限，没有做前端界面权限吗

**Comment by 91270** [comment]
有的啊

**Comment by AlexMercerGitHub** [comment]
> 有的啊

请问是在哪个页面呢，我在demo那边菜单都寻找了，没有找到定义按钮是否显示，只有菜单的是否显示

**Comment by 91270** [comment]
角色权限，用来分配 页面，及按钮的权限，
数据权限，用来分配 不同用户 ，同一个页面，可查数据的范围，（数据权限在基础定义中配置。相当于组织架构）

![image](https://user-images.githubusercontent.com/61639203/102565901-56222c00-4119-11eb-9203-a164b49628b2.png)

**Comment by AlexMercerGitHub** [comment]
> 角色权限，用来分配 页面，及按钮的权限，
> 数据权限，用来分配 不同用户 ，同一个页面，可查数据的范围，（数据权限在基础定义中配置。相当于组织架构）
> 
> ![image](https://user-images.githubusercontent.com/61639203/102565901-56222c00-4119-11eb-9203-a164b49628b2.png)

角色权限 是控制页面按钮隐藏和不可用的。如果希望制定某个用户在页面的字段(不是按钮，例如输入框)不可见，不可编辑，目前系统是没有做的吧

**Comment by 91270** [comment]
没有做到字段的控制。这种实际操作起来过于复杂了

**Comment by AlexMercerGitHub** [comment]
> 没有做到字段的控制。这种实际操作起来过于复杂了

是的。感谢指教
