### ISSUE TITLE
vs2019(16.8.4)  启动运行时报错

### ISSUE THREAD

**Issue by minvision** [91270/Meiam.System#15]
2>------ 已启动生成: 项目: Meiam.System.Hostd, 配置: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1662,5): error MSB4062: 未能从程序集 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll 加载任务“NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask”。程序集“NuGet.Build.Tasks, Version=5.8.1.7021, Culture=neutral, PublicKeyToken=31bf3856ad364e35”中的类型“NuGet.Build.Tasks.RestoreTask”的方法“get_BuildEngine”没有实现。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。

**Comment by 91270** [comment]
应该是您开发环境问题

**Comment by minvision** [comment]
> 应该是您开发环境问题

兄弟接外包不？

**Comment by 91270** [comment]
有什么需求
