### ISSUE TITLE
不曉得該如何正確配置，像是Redis沒正常運行。

### ISSUE THREAD

**Issue by yishiang0217** [91270/Meiam.System#16]
@91270 原作者您好，
修改完appsettings.json Nlog.Config的配置，有跳出Swagger文件的畫面，
但依然沒辦法正常運行(嘗試發出Web API請求就會報錯)，想請你幫忙看看，謝謝。

截圖在這兒: https://imgur.com/a/MAO4yzr

[https://imgur.com/a/MAO4yzr](url)

**Comment by 91270** [comment]
是的，你需要安装　REDIS 服务端

**Comment by yishiang0217** [comment]
@91270 原來如此，謝謝回覆哦。

另想請問如果不用Redis能運行嗎? 要修改哪一行呢…

**Comment by 91270** [comment]
项目部分功能依赖于 REDIS ，所有必须使用
