### ISSUE TITLE
发布部署失败

### ISSUE THREAD

**Issue by wqqwqq666** [91270/Meiam.System#18]
web api 和 前端都已经发布到IIS里面，可是两个站点都打不开，直接报404错误
 web api 发布到本机IIS下的9014端口，
  http://127.0.0.1:9014/
然后访问显示 404，
![图片](https://user-images.githubusercontent.com/15796964/107009530-25cd4480-67d0-11eb-9a79-1196cc46fa43.png)

**Comment by 91270** [comment]
应该是你 IIS 配置问题，我这边不管是 IIS 模式  或  Host 模式，启动都没有问题

**Comment by wqqwqq666** [comment]
问题已经解决，需要一个IIS关于VUE的重定向插件，和一个web host
