### ISSUE TITLE
很棒的项目

### ISSUE THREAD

**Issue by yeungxh** [91270/Meiam.System#2]
代码很工整，没有冗余，架构思路也容易理解，很适合我这样的小白新手。期待以后保持更新，没有联系方式，特意开个issue鼓励一下。

**Comment by 91270** [comment]
谢谢支持！

**Comment by yeungxh** [comment]
> 谢谢支持！

目前还是单库的，我的需求是有多个已有的数据库的，不知道该怎么改，还有异步

**Comment by 91270** [comment]
这个需要具体看你业务，才可以进一步扩展
