### ISSUE TITLE
关于RedisCache类的问题

### ISSUE THREAD

**Issue by loveyeguo** [91270/Meiam.System#29]
`     public void Remove<V>(string key)
        {
            RedisServer.Cache.Del(key.Remove(0, 6));
        }`

为什么需要Remove(0,6)? 是不是写错了

**Comment by loveyeguo** [comment]
>   public IEnumerable<string> GetAllKey<V>()
        {
            return RedisServer.Cache.Keys("Cache:SqlSugarDataCache.*");
        }

还有  这里应该改为 

>   public IEnumerable<string> GetAllKey<V>()
        {
            return RedisServer.Cache.Keys("Cache:.*");
        }

**Comment by 91270** [comment]
这个类是 Sqlsugar 的扩展，你应该是用 Sqlsugar .WithCache  进行缓存，然后再使用 RemoveCache 跟踪下，你就明白了
