### ISSUE TITLE
项目好像完全不能用了，各种报错

### ISSUE THREAD

**Issue by wqqwqq666** [91270/Meiam.System#32]
大家是否遇到下面的情况
![image](https://user-images.githubusercontent.com/15796964/146524134-e9f7c010-4623-4639-8abd-09a83a049140.png)

**Comment by wqqwqq666** [comment]
大神看到麻烦发个压缩包给我把，邮箱：942035249@qq.com

**Comment by Zhangyling-Dev** [comment]
今天打算跑一下这个框架，结果报错与楼主是相同的

**Comment by 91270** [comment]
npm 版本问题 ，更换 6.14.x
