### ISSUE TITLE
关于多系统设置

### ISSUE THREAD

**Issue by xulei-Itachi** [91270/Meiam.System#33]
字典定义中，预置了"SYSTEM_MENU_SYSTEM",那后续该如何使用?
大致看了一下，好像只有"菜单管理"功能可以根据对应系统进行区分设置。
其他涉及到权限管控的地方，似乎并没有做区分。
我尝试在预设的"微信小程序"系统下添加了菜单，但是在权限定义以及其他权限管理的地方并不能看到相应菜单信息。
另外，该Admin设计中，新增页面的浏览权限，必须要认为在"权限定义"中维护才行吗？这样似乎有些繁琐。

**Comment by 91270** [comment]
这个是菜单接口上使用的，接口获取的时候根据 字典定义的参数，可以拉去不同系统的菜单列表
