### ISSUE TITLE
Vue前端安装依赖失败

### ISSUE THREAD

**Issue by Zhangyling-Dev** [91270/Meiam.System#38]
好像以前有这个问题，是我的npm 版本有问题？
![image](https://user-images.githubusercontent.com/72442626/218480466-3ad1b675-0524-4224-a149-b2e1c3118c1e.png)

**Comment by 91270** [comment]
我这是用的是 6.14.x

**Comment by Zhangyling-Dev** [comment]
谢谢解答，已经运行起来了。
