### ISSUE TITLE
大佬，项目跑起来，接口时间特别长

### ISSUE THREAD

**Issue by tcmld** [91270/Meiam.System#6]
大佬，项目跑起来了，后台接口时间特别长，获取验证码用了一分钟
游览器上看，验证码的数据瞬间出来，但是还一直转圈，要等一分钟左右才停，F12查看 content download 时间都在这里消耗了

**Comment by 91270** [comment]
应该是第一次启动，程序预热造成的吧

**Comment by 91270** [comment]
你检查一下是不是你 Nlog.Config 的数据库连接没有修改

**Comment by LossHu** [comment]
大概率是Nlog.Config 数据库配置，更改后路记得重新生成。我昨天也遇见了改了半天配置没生效。

**Comment by tcmld** [comment]
是的，我解决了，就是这个问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "91270/Meiam.System"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 上午8:41
收件人:&nbsp;"91270/Meiam.System"<Meiam.System@noreply.github.com&gt;;
抄送:&nbsp;"懒虫"<631342891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [91270/Meiam.System] 大佬，项目跑起来，接口时间特别长 (#6)





 
大概率是Nlog.Config 数据库配置，更改后路记得重新生成。我昨天也遇见了改了半天配置没生效。
