### ISSUE TITLE
编释不通过 找不到 userSession.Administrator 

### ISSUE THREAD

**Issue by DotNetNext** [91270/Meiam.System#7]
predicate = predicate.AndIF(!userSession.Administrator, m => m.Administrator == false);、

是不是有代码没签进去

**Comment by icecn324** [comment]
我刚下载的也有这个问题，应该是UserSessionVM和Sys_Role这两个类没有签入，另外数据库生成sql这个字段也别忘记添加哈

**Comment by 91270** [comment]
已经更新
