### ISSUE TITLE
可以试试使用jwt作为token，这样可以承载更多信息。

### ISSUE THREAD

**Issue by LossHu** [91270/Meiam.System#9]

**Comment by 91270** [comment]
我不使用 JWT 的原因有以下几点：
1、不想在客户端存放过多的信息
2、针对注销场景、修改密码、会话管理、用户提出等业务场景，处理起来比较麻烦
3、无法保持同一TOKEN自动续期
4、多种应用客户端使用麻烦
5、不方便对 TOKEN 承载的信息进行更新

**Comment by LossHu** [comment]
这只是我的建议，这套系统过分依赖于redis缓存，当缓存出现问题时整体都不可用，如果要这样做的话也可以考虑下redis集群，保证系统的稳定。

**Comment by 91270** [comment]
是的，这个系统起构建的时候是针对企业数采所使用的。由于客户端种类较多。所以TOKEN所要携带的信息比较多，同时可能会随时增加信息。我们项目实际也是采用的REDIS集群。提升REDIS可用性，而且横向扩容也比较方便，对于业务数据缓存很少缓存，进行缓存的内容大多是配置和基础数据。
